### PR TITLE
Add Vassals

### LINKED ISSUE #82: Add Vassals
The goal of this issue is to implement the Vassals mechanic, as added by the Mother of Dragons extensions. This would allow players to turn unpicked houses into Vassals in the game.

### LINKED ISSUE #641: Allow a player to be replaced by a Vassal
Once Vassals are implemented, the idea of this issue would be to allow players to be replaced by vassals when they no longer want to participate in the game, or because someone want inactive.

### PR DESCRIPTION
**Pull request by Longwelwind**
Closes #82
Closes #641 

Sub-tasks:

- [x] Add vassal-able houses, accompanied with a picking phase happening at the beginning of the Planning phase.
- [x] Implement the fact that Vassals' orders are placed after players' orders.
- [x] Implement special orders for vassals
- [x] Add special vassals House cards mechanics
- [x] Define vassal house setups
- [x] Make vassals an optional game setting
- [x] Add vote to replace a player (including themselves) by a vassal
- [x] Make sure the rest of the game work with the addition of vassals:
  - [x] Make sure Vassals can't win the game
  - [x] Make sure Vassals can't hold dominance token
  - [x] Make sure Vassals can't bid in any CoK
  - [x] Make sure that Vassals don't bid in Wildling attack and are immune
  - [x] Vassals muster only in their home area
  - [x] A commander can use his Valyrian Steel Blade for his vassal
  - [x] A commander cannot use his Raven for a vassal
  - [x] A commander wins a PT when one of their vassal wins a combat
  - [x] A vassal always leave a PT when leaving a region
  - [x] A commander cannot march into a region or raid a region controlled by one of its vassals.
  - [x] A Vassal cannot march into a region or raid a region controlled by its commander or an other vassal of its commander.
  - [x] Vassal family members can't support against each other (FAQv2)
- [x] Create the necessary migrations
  - [x] Migrate `PlanningGameState` to the new sub-tree of GameStates
  - [x] Migrate `ResolveRaidOrderGameState` and init `resolvedRaidSupportOrderRegions`
  - [x] game.vassalHouseCards
  - [x] game.vassalRelations
  - [x] chooseHouseCard.choosableHouseCards

### CODE REVIEW

**Comment by Dode123** [comment]
This is a list of things that Long needs to remember to check before putting this branch live ^^ 

- Vassals do not bid in wildling attacks, are immune to its effects, and cannot be chosen as lowest/highest bidder. 
- Westeros "mustering" card only allows the vassal commander to muster at their home area. (if they lost their home area, then will not receive mustering from this card). 
- Vassal order planning phase is AFTER all player houses have assigned their orders. 
- Vassals automatically places power tokens behind when marching.
- Vassals have an infinite amount of power tokens (used for leaving control when marching). 
- In 3 player games, the player on the highest position of the Iron Throne starts with two vassal sets.
- Special rule for Targaryen regarding vassal picking phase: Cannot pass a vassal, and will automatically receive all remaining vassals to command. 
- Special rule for dominance effects on vassals: A commander **CAN** use steel blade on behalf of his vassal, but **CANNOT** use raven to swap a vassal order.
- When a vassal win a battle, its commander get a power token.

**Comment by phi1-h** [comment]
Have a look at https://git.sr.ht/~phi1_h/GoT_Boardgame/tree/master/static the map and house logos might be interesting, if you still need some of those.

**Comment by gereon77** [comment]
- [ ] Vassals may only place 2 orders
- [ ] Disable auto resolving of Raid orders for vassals as they may want to be used as Support later
- [ ] Disallow Unready for non vassal houses when placing vassal orders

**Comment by gereon77** [comment]
WTF... Looks like my IDE did some shit here...

**Comment by gereon77** [comment]
DWD Vassal setup is missing

**Pull request merged**
