### PR TITLE
Add tooltip with remaining Westeros cards

### LINKED ISSUE #208: Visualize Westeros card discard pile card count
To avoid scrolling the whole game log for probabilities.

The game right now doesn‘t implement a discard pile but puts the drawn card back to deck at the end. But there is a Westeros discard pile:

958E8A02-E51B-46F8-B03E-C90900489CDB

### PR DESCRIPTION
**Pull request by gereon77**
Closes #208 

Today I thought let's make it right. I struggled a bit with the tooltip design and I am not totally satisfied but it is better than nothing. Feel free to take the logical part of this PR and redesign it. Atm it is shown when hovering over the phases bar.

Preview:

image

### CODE REVIEW

**Comment by gereon77** [comment]
To compress it a bit I could do `joinReactNodes(..., <br/>)` instead of `<p></p>`. I will post a preview for that here later.

**Comment by norielbit** [comment]
This feels a bit obscure within the UI for me. The Round counter / Wildling Threat row is mostly empty in the UI, what do you think of utilizing it, something like this:

image
The text is a bit hard to read, from left to right the things in the red rectangle are:
MoD IV deck, AFfC missions, Tides of Battle and Wildlings imo can show the Wildling deck on hover.
It's a bit crowded if all the icons are there but ignoring custom modes the IV and mission decks are mutually exclusive so that only 2 of the things in the rectangle may appear at once (ToB + IV or missions).

Ideally, I think the ability to look them by image or a short description is important. Something like "no raids orders". Especially for the III deck its hard to remember all the cards, at least for me. This of course should wait for a different PR.

Unrelated to this PR, but can we make it so that when the raven holder knows what the top card is, they can see it while hovering the Wildling icon?

**Comment by Longwelwind** [comment]
It's a bit rough, but it works, and at least, it gives the info. I'll merge, we can discuss on how to better display it in the issue.

>Unrelated to this PR, but can we make it so that when the raven holder knows what the top card is, they can see it while hovering the Wildling icon?

You can create an issue for this, I can then explain how to implement it. 🙂

**Comment by norielbit** [comment]
> It's a bit rough, but it works, and at least, it gives the info. I'll merge, we can discuss on how to better display it in the issue.

Sure

> > Unrelated to this PR, but can we make it so that when the raven holder knows what the top card is, they can see it while hovering the Wildling icon?
> 
> You can create an issue for this, I can then explain how to implement it. 🙂

There's already an issue for it, #245 I'll just mention it there

**Comment by gereon77** [comment]
Unfortunately it doesn’t work for mobile :/

**Pull request merged**
