### PR TITLE
Apply Kings Court overlay when playing with 4 player or less

### PR DESCRIPTION
**Pull request by gereon77**

### CODE REVIEW

**Comment by Longwelwind** [comment]
We should aim for a more generic version, I think. Let's say that in `baseGameData`, we store the count of starred orders:

```json
"starredOrderRestrictions": [
  [4, [3, 2, 1]],
  [8, [3, 3, 2, 1]]
]
```

We should then be able to retrieve the right `starredOrderRestrictions` based on the number of players.

**Comment by gereon77** [comment]
True. But in fact it should be 

```json
 "starredOrderRestrictions": [
   [4, [3, 2, 1]],
   [6, [3, 3, 2, 1]],
   [8, [3, 3, 2, 1, 0, 0, 0, 3]]
 ]
```

or what about

```json
 "starredOrderRestrictions": [
   [3, 2, 1, 0],
   [3, 3, 2, 1, 0, 0],
   [3, 3, 2, 1, 0, 0, 0, 3]
 ]
```

and using array.length for the check?

In addition when implementing vassals it is important that a vassal is a house so that at least 6 houses will participate always and the King's Court overlay won't come into play...

**Comment by gereon77** [comment]
ok now?

**Comment by Longwelwind** [comment]
There are better ways to implement the loop (using `findIndex`) but it will do for now.

Thanks for the PR!

**Pull request merged**
