### PR TITLE
Fix sea regions can additionally raid land regions

### PR DESCRIPTION
**Pull request by gereon77**
I found this bug when playing around with "Removing unused raid orders“.

### CODE REVIEW

**Comment by gereon77** [comment]
Any chance to apply this to the already created games?

**Comment by Longwelwind** [comment]
Merged and deployed 😄

**Comment by gereon77** [comment]
> Merged and deployed 😄

But from what I see it won’t affect already created games as world is created once and the sea kind without the additional raid thing is already set..

**Comment by Longwelwind** [comment]
`regionTypes` are statically defined entities and not loaded from the serialized game. This means that modifications on them are directly applied to all games.

**Comment by gereon77** [comment]
Perfect!

**Pull request merged**
