### PR TITLE
Allow users to set unready again during planning phase

### LINKED ISSUE #88: Changing orders should be acknowledged by a button
Right now you only have to acknowledge your orders the first time. Any changes to your orders are sent directly to the server which might lead to a critical state.
It would be better if your changes will be submitted on a button which appears when you changed your already sent orders.

### LINKED ISSUE #460: The rule to set an order to each region which is controlled by a unit can be bypassed
After user hits the Ready button he can remove an order from the board which is a cheat. It would make sense to adapt #283 so the user only can change orders when game is in unready state.

@Longwelwind A long time ago you said on Discord that you imagined sth different and will describe it in the PR. I still wait for that. :)

### PR DESCRIPTION
**Pull request by gereon77**
Closes #88 
Closes #460

### CODE REVIEW

**Comment by gereon77** [comment]
I can rebase it to master if desired...

**Comment by Longwelwind** [comment]
If you can, yeah, that'd be good

**Comment by gereon77** [comment]
NP. One moment. But I guess i have to PR it again because it’s already merged to 1.4

**Comment by gereon77** [comment]
And merging `PlanningGameState` is a bit more complicated now. Give me a few minutes.

**Pull request merged**
