### PR TITLE
Trim white edges off card corners, and slightly increase saturation.

### PR DESCRIPTION
**Pull request by alecejones-noodoe**

### CODE REVIEW

**Comment by gereon77** [comment]
LGTM. Can you do the same for the garrsion in Pentos and Braavos?

**Comment by alecejones-noodoe** [comment]
done

**Comment by gereon77** [comment]
Well Braavos still shows white corners:

image

**Comment by alecejones-noodoe** [comment]
Almost certainly a file caching issue, you can see the raw file shows the corners are gone

**Comment by gereon77** [comment]
Nah I guess sth went wrong with the commit. There is no transparency on the raw file as well.

**Comment by gereon77** [comment]
Sorry. I downloaded the file directly from the page and there it is good. Idk what happened locally...

**Comment by alecejones-noodoe** [comment]
Sorry, forgot to mention that i also did the eyrie-6, which also was missing the necessary changes

**Pull request merged**
