### PR TITLE
Add modified essos map

### PR DESCRIPTION
**Pull request by alecejones-noodoe**
Performed slight modification of Essos map, including slightly increased lightness and saturation and reduction of shadows. This is especially noticeable with the shadows on the left side of the board. Open to further discussion on how this map can be improved before merging.

### CODE REVIEW

**Comment by gereon77** [comment]
This file is not compatible with the webpack image loader and cause a runtime error…

**Comment by alecejones-noodoe** [comment]
What's the error? I literally just modified the shading and saved it, no format change or anything.

**Comment by alecejones-noodoe** [comment]
I force pushed a newer, compressed version. See if that works.

**Comment by gereon77** [comment]
@alecejones-noodoe This map seems to be good and the reduced size with that quality is impressive! Many Thanks! I wait the with merging though as your PR is now one commit behind master and there is a new feature to rebase via the UI but Longwelwind has to enable it first: https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests

After it's done, I'll merge!

**Comment by alecejones-noodoe** [comment]
Don't thank me, thank the nameless engineers who built the online jpeg compression tool.

**Pull request merged**
