### PR TITLE
Dance with dragons

### PR DESCRIPTION
**Pull request by andisichert**
All house card pictures

### CODE REVIEW

**Comment by andisichert** [comment]
wrong fork

**Comment by gereon77** [comment]
@andisichert In case you have a working solution for ADWD we are very interested to make it public :)

**Comment by andisichert** [comment]
@gereon77 me and @riegerflo are working on it at the moment. Give us some weeks :)

**Comment by gereon77** [comment]
@andisichert Nice one! Do you host your version  somewhere on your own? I would appreciate your help here as I am no Docker expert and all the hosting stuff was done by Long but unfortunately he doesn’t have that much time for the platform at the moment and therefore we never managed to set up my private instance...

**Comment by gereon77** [comment]
@andisichert @riegerflo 

Another contributor was faster. We have ADWD now on the master branch :)

**Comment by riegerflo** [comment]
> @andisichert @riegerflo
> 
> Another contributor was faster. We have ADWD now on the master branch :)

Thx @gereon77 for letting us know! Good to hear that we can play ADWD now ☺️ @andisichert it was a good exercise though 😄

**Pull request closed without merging**
