### PR TITLE
Lowest bidder for The Horde Descends now has to select two units of the same stronghold/castle if able.

### LINKED ISSUE #604: Lowest bidder effect of „The horde descends“ allows to pick 2 units from different castles
ED88389A-207B-40D9-95F1-51E2CA48D0A4

### PR DESCRIPTION
**Pull request by gereon77**
Fix #604 

Ideally the selectable units would dynamically change if the first unit was selected. But this would be a bigger change so I guess this is ok as first fix.

### CODE REVIEW

**Comment by Longwelwind** [comment]
Do you handle the case where all strongholds only have one unit?

**Comment by gereon77** [comment]
I guess they are filtered out in firstStart()

**Comment by gereon77** [comment]
Selectable units now dynamically change after first unit has been selected. In fact it wasn't that difficult. My brain was just not working correctly...

**Comment by Longwelwind** [comment]
I'll merge it so it's done, but it's clearly not the best solution. `SelectUnitsGameState` has become unmaintainable with all the small hacks that we added over the time.

I'll let it like this right now. I hope it won't incur too much technical debt when MoD's special mechanics will need to be taken into account.

**Pull request merged**
