### PR TITLE
Add game logs for different House cards

### LINKED ISSUE #192: Cercei Lannister can be activated even if there is no valid order to remove
And this leads to a stalled game:

image

### PR DESCRIPTION
**Pull request by Longwelwind**
Closes #192

### CODE REVIEW

**Comment by Longwelwind** [comment]
Relates to #17

**Comment by Longwelwind** [comment]
@gereon77 Do you think you'd have time to test this and give me some feedback? It adds game logs for all _actionnable_ house cards (where a player must do an effect).

**Comment by gereon77** [comment]
@Longwelwind I'll try to do it until no later than tomorrow night

**Comment by Longwelwind** [comment]
I'll merge it, even if it is not properly tested.

We'll playtest the different game logs that are produced.

**Pull request merged**
