### PR TITLE
Add Tides of Battle card images.

### PR DESCRIPTION
**Pull request by mrhappyasthma**
I wasn't exactly sure of the best names for the files, since these cards are nameless. I tried to keep it simple and describe what the card provides.

This is part of Tides of Battle: https://github.com/Longwelwind/swords-and-ravens/issues/561

### CODE REVIEW

**Comment by Longwelwind** [comment]
Note: we'll need to reduce the size of the cards if we implement Tides of Battles.

Do you think you could rebase this off `master`? If you don't know how to do it, fire me a message on Discord and I'll tell you how to do it :)

**Comment by mrhappyasthma** [comment]
Do you have a target size/resolution in mind?

**Comment by mrhappyasthma** [comment]
Rebased. Also changed the image size significantly to reduce its file size.

I just chose something reasonable. Let me know if you think it should be larger or smaller.

**Comment by Longwelwind** [comment]
Looks good, I'll merge!

**Pull request merged**
