### PR TITLE
WIP: Begin DeclareSupportGameState with attacker and defender

### PR DESCRIPTION
**Pull request by gereon77**
This differs from the declaration of the state by Errata v2 but as discussed on Discord we should do it that way to speed up this phase a bit.

### CODE REVIEW

**Comment by Longwelwind** [comment]
Not sure about this; this modification differs from the rule. Otoh, I think a situation where the order of support declaration is important is rare.

Also, wouldn't #407 makes this redundant?

**Comment by gereon77** [comment]
Yea #407 would make this PR obsolete. But as described in the issue speeding up this state via changing resolve order seems to be the better solution.

Automatically declaring support for all other houses than GJ and Stark is no real option. And I guess this checkbox might be problematic for battles where you are defender. Users will tend to forget to uncheck it and then the support is given although you wanted to decline it for this battle...

**Comment by gereon77** [comment]
Delgado has thrown in a nice idea. I will describe it in #407 .

**Comment by Longwelwind** [comment]
I prefer this idea too. Therefore I'll close this PR if that's okay with you.

**Pull request closed without merging**
