### PR TITLE
Fix multiple things

### PR DESCRIPTION
**Pull request by gereon77**
This are all things I came over when implementing the other things.

Each commit should be easy to review.

Regarding the remove ships commit: That should enable a 3p game just without the infinitely garrisons and was easy to do.
I just wondered that TS allows accessing the array in its foreach loop. C# forbids that and I wonder if i should map the unit ids before? Nevertheless it works this way.

### CODE REVIEW

**Comment by Longwelwind** [comment]
* `Don't evaluate canLeavePowerToken when player haven't left one`: I don't mind this kind of chnages because it doesn't reduce readability, but I want to make it clear that this is clearly [micro-optimization](https://softwareengineering.stackexchange.com/questions/99445/is-micro-optimisation-important-when-coding). If this change would have added lines and/or code complexity, I'd have refuse it.
* `Remove ships in Port of Lannisport if there are no units in Pyke`: It's not the right way to do this. We should implement a mutator feature for games later and maybe allow an option for this.
* `Disable submit button when user did not muster anything. Fixes empty …`: IIRC, the goal of letting this is to allow a house to resolve the starred consolidate power without mustering anything and without gaining any power tokens, which is allowed.

**Comment by gereon77** [comment]
I see. I remove the Lannisport thing and keep that on an own branch for self hosted games until this option is available :)

Regarding Disable submit button.. the thing is that it is also fixed by the other commit with the wrong check.. but if you want to allow resolving a CP with nothing (i don’t know if that makes sense at all) then we have to fix that no muster is rejected by the server. That’s why you can spam the game log with „house mustered“ messages. See comment in #134

**Comment by gereon77** [comment]
@Longwelwind I removed the 2 commits.

**Comment by Longwelwind** [comment]
Ok, the rest is perfect! Can you rebase on master so that I can merge?

Thanks for the PR, as always!

**Comment by gereon77** [comment]
@Longwelwind Done. :)

**Pull request merged**
